### ISSUE TITLE
`hasDynamicImport` with eval dynamic import

### ISSUE THREAD

**Issue by legendecas** [tc39/proposal-esm-phase-imports#14]
Could `AbstractModuleSource.prototype.hasDynamicImport` determinisitically be `true` if the module contains dynamic imports via eval?

**Comment by guybedford** [comment]
This is a great point, thanks. This may be justification to remove this feature, I'll post a PR.

**Comment by Jack-Works** [comment]
In this case, the dynamic import will have no context (for resolving a relative module) IMO. I don't want this feature to be removed.

**Comment by guybedford** [comment]
In Node.js, I get the following:

subfolder/mod.mjs
```
eval("import('./dep.mjs')");
```

Attempting to load `subfolder/dep.mjs`. So the context works fine I believe?

**Comment by Jack-Works** [comment]
I also tried this and dug into the spec. Yes, it will have the context, even indirect eval works, so it's ok to remove `hasDynamicImport`

**Comment by guybedford** [comment]
Thanks for the follow-up. Since it is so close to the meeting, I will leave the PR open for now.

**Comment by legendecas** [comment]
It depends on if the eval is a direct eval. If it is an indirect eval, it depends on whether the host propagates the active script properly (actually, it's not https://github.com/tc39/ecma262/pull/3195).

**Comment by guybedford** [comment]
Removed in https://github.com/tc39/proposal-esm-phase-imports/pull/15.
