### ISSUE TITLE
Performance data

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-esm-phase-imports#8]
Since one of the major motivations here is performance, do we already have some numbers that we can take a look at?

**Comment by guybedford** [comment]
Performance is actually not a justification for this proposal at all.

**Comment by codehag** [comment]
I see, so the justification here is static analysis, and ergonomics, is that right? You can close this issue in that case.

**Comment by guybedford** [comment]
> I see, so the justification here is static analysis, and ergonomics, is that right? 

And also portability, yes. Performance may improve as a side effect, but the full graph is only fetched at the time of the worker invocation. Preloading this graph before the worker call is not a focus of this proposal, the other justifications are.

Ok, will close, but happy to pick up on any of these aspects as needed.
